import { Question } from './types';

export const scenarioQuestions: Question[] = [
  { id: 's1', category: 'Scenario & Projects', question: 'Scenario (Project 1): PC-A on VLAN 10 cannot ping PC-B on VLAN 20. What do you check?', answer: 'First, I verify IP and subnet masks on both PCs. Second, I check if the switch ports are assigned to correct VLANs. Third, since they are on different VLANs, I ensure an Inter-VLAN routing mechanism (like Router-on-a-stick) is configured. I would check the trunk link between the switch and router, and verify sub-interfaces and 802.1Q encapsulation on the router.', difficulty: 'Advanced' },
  { id: 's2', category: 'Scenario & Projects', question: 'Scenario (Project 2): Your Vercel deployment fails during the build phase. How do you troubleshoot?', answer: 'I would open the Vercel dashboard and inspect the build logs. Common issues include missing dependencies in `package.json`, TypeScript errors, or missing environment variables. I would replicate the build command (`npm run build`) locally to see if it fails on my machine, fix the issue, and push the code back to GitHub to re-trigger the pipeline.', difficulty: 'Advanced' },
  { id: 's3', category: 'Scenario & Projects', question: 'Scenario (Project 3): A user complains they cannot access the Samba share. Steps to resolve?', answer: '1. Check if the `smbd` service is running on the Linux server. 2. Verify network connectivity (`ping`). 3. Check the Linux firewall/iptables to ensure Samba ports (139/445) are open. 4. Verify the user has been added to Samba (`smbpasswd -a user`). 5. Check Linux directory permissions and SELinux context (on CentOS) for the shared folder.', difficulty: 'Advanced' },
  { id: 's4', category: 'Scenario & Projects', question: 'Scenario (Project 4): You launched an EC2 instance, installed Apache, but cannot access the IP in a browser. Why?', answer: 'The most common reason is the EC2 Security Group. I would check the AWS Management Console to ensure the Security Group attached to the instance has an Inbound Rule allowing HTTP (Port 80) traffic from Anywhere (0.0.0.0/0). I would also SSH into the instance to ensure `apache2` or `httpd` service is actually running.', difficulty: 'Advanced' },
  { id: 's5', category: 'Scenario & Projects', question: 'How do you use AI Tools (ChatGPT/Gemini) in your daily workflow?', answer: 'I use AI tools to accelerate troubleshooting and development. For example, if I encounter an obscure Linux error code, I paste the log into Gemini to quickly identify the root cause. I also use it to generate boilerplate Ansible playbooks, understand complex bash scripts, or clarify networking concepts. I always review and test the AI output in a safe lab before deploying to production.', difficulty: 'Intermediate' },
  { id: 's6', category: 'Scenario & Projects', question: 'Scenario: Your Linux server\'s root partition is 100% full. How do you fix it without rebooting?', answer: 'First, I use `df -h` to confirm the partition is full. Then I use `du -sh /*` to find large directories, drilling down to find unnecessary large log files or temp files. I can truncate large active logs without breaking processes by using `> /var/log/large_file.log`. If it is an LVM volume, I can add a disk, extend the volume group, and extend the logical volume and filesystem online.', difficulty: 'Advanced' },
  { id: 's7', category: 'Scenario & Projects', question: 'Scenario: You accidentally locked yourself out of an EC2 instance by messing up the SSH keys. How do you regain access?', answer: 'Stop the EC2 instance, detach its root EBS volume, and attach that volume to a temporary recovery EC2 instance. Mount the volume, fix the `~/.ssh/authorized_keys` file, unmount it, detach it from the recovery instance, and reattach it back to the original instance as the root device (/dev/sda1). Finally, start the original instance.', difficulty: 'Advanced' },
  { id: 's8', category: 'Scenario & Projects', question: 'Scenario: You are configuring a switch and accidentally typed `switchport mode access` on the trunk link to the router. What happens?', answer: 'The trunk link will immediately convert to an access link in VLAN 1. Inter-VLAN routing will break because 802.1Q tags will no longer be sent. Only traffic from the native/default VLAN will make it to the router. I would fix it by entering the interface configuration and typing `switchport mode trunk`.', difficulty: 'Advanced' },
  { id: 's9', category: 'Scenario & Projects', question: 'Scenario: Jenkins build pipeline is taking 45 minutes instead of 5 minutes. How do you troubleshoot?', answer: 'I would look at the Jenkins Console Output to identify which specific build step is hanging. Typical culprits are network timeouts (trying to download dependencies from a blocked registry), hanging automated tests, or lack of compute resources on the Jenkins agent (check CPU/RAM on the EC2 instance).', difficulty: 'Advanced' },
  { id: 's10', category: 'Scenario & Projects', question: 'Scenario: A database query is running very slowly on MariaDB. What is your first step?', answer: 'I would log into MariaDB and use the `SHOW PROCESSLIST;` command to see what queries are currently running and if any are locked. I would also prefix the slow query with the `EXPLAIN` keyword to see how the database engine is executing the query and determine if proper indexes are being used.', difficulty: 'Advanced' }
];
