import { Question } from './types';

export const devopsQuestions: Question[] = [
  { id: 'd1', category: 'DevOps & CI/CD', question: 'What is CI/CD, and how did you implement it using GitHub and Vercel?', answer: 'CI/CD stands for Continuous Integration and Continuous Deployment. It automates the testing and deployment of code. In my e-commerce project, I connected my GitHub repository to Vercel. Whenever I pushed new code to the main branch, a webhook triggered Vercel to automatically build the application and deploy it live with zero manual steps.', difficulty: 'Intermediate' },
  { id: 'd2', category: 'DevOps & CI/CD', question: 'What is Jenkins, and how did you use it on your AWS EC2 instance?', answer: 'Jenkins is an open-source automation server used to build CI/CD pipelines. I installed it on my Ubuntu EC2 instance. I configured automated build jobs that would pull source code from a repository, run necessary build commands, and deploy the application, eliminating the need to manually execute deployments.', difficulty: 'Intermediate' },
  { id: 'd3', category: 'DevOps & CI/CD', question: 'What is Ansible, and how is it different from traditional shell scripting?', answer: 'Ansible is an open-source configuration management and IT automation tool. Unlike shell scripts, Ansible is declarative (you state the desired state, and Ansible achieves it) and agentless (it connects via SSH). It uses YAML playbooks which are easier to read, maintain, and scale across hundreds of servers compared to custom shell scripts.', difficulty: 'Intermediate' },
  { id: 'd4', category: 'DevOps & CI/CD', question: 'What are Git and GitHub? Explain the basic Git workflow.', answer: 'Git is a distributed version control system used locally to track changes in code. GitHub is a cloud platform for hosting Git repositories. A basic workflow: `git clone` (download repo), `git add .` (stage changes), `git commit -m "message"` (save changes locally), and `git push` (upload changes to GitHub).', difficulty: 'Basic' },
  { id: 'd5', category: 'DevOps & CI/CD', question: 'What is the purpose of a Jenkinsfile?', answer: 'A Jenkinsfile is a text file that contains the definition of a Jenkins Pipeline as code (Groovy syntax). It is checked into the source control repository, allowing the CI/CD pipeline logic to be versioned and reviewed alongside the application code.', difficulty: 'Intermediate' },
  { id: 'd6', category: 'DevOps & CI/CD', question: 'Explain the difference between Continuous Delivery and Continuous Deployment.', answer: 'Continuous Delivery means code changes are automatically built, tested, and prepared for a release to production, but the final deployment requires a manual approval step. Continuous Deployment automates the entire process, where every change that passes tests is automatically deployed to production without human intervention.', difficulty: 'Advanced' },
  { id: 'd7', category: 'DevOps & CI/CD', question: 'How do you handle secrets/passwords in Ansible?', answer: 'Ansible uses Ansible Vault to encrypt sensitive data, such as passwords, API keys, or SSL certificates, rather than storing them in plain text in playbooks. You encrypt the file using `ansible-vault encrypt` and run playbooks providing the vault password.', difficulty: 'Advanced' },
  { id: 'd8', category: 'DevOps & CI/CD', question: 'What is an Ansible Playbook, and what format is it written in?', answer: 'An Ansible Playbook is a file that contains a series of tasks/instructions that Ansible should execute on target remote nodes. They are written in YAML (Yet Another Markup Language).', difficulty: 'Basic' },
  { id: 'd9', category: 'DevOps & CI/CD', question: 'What is the `git rebase` command?', answer: '`git rebase` is used to integrate changes from one branch into another. Unlike `git merge`, which creates a new merge commit, rebase rewrites the commit history by moving the base of your branch to the tip of another, creating a cleaner, linear history.', difficulty: 'Advanced' },
  { id: 'd10', category: 'DevOps & CI/CD', question: 'How does Vercel know when to deploy a new version?', answer: 'Vercel sets up a webhook on the connected Git repository (like GitHub). When a `git push` event occurs on the configured deployment branch (usually `main`), GitHub sends a payload to Vercel via the webhook, triggering Vercel to clone the new code, build it, and deploy it.', difficulty: 'Intermediate' },
  { id: 'd11', category: 'DevOps & CI/CD', question: 'How do you resolve a Git merge conflict?', answer: 'A merge conflict occurs when two branches have competing changes on the same lines of code. To resolve it: 1. Git marks the conflicted areas in the file. 2. Manually edit the file to choose which changes to keep. 3. Remove the conflict markers (<<<<, ===, >>>>). 4. Stage the file with `git add`. 5. Complete the merge with `git commit`.', difficulty: 'Intermediate' },
  { id: 'd12', category: 'DevOps & CI/CD', question: 'What are Jenkins Plugins?', answer: 'Plugins are extensions that add specific capabilities to Jenkins. Since Jenkins is highly extensible, you use plugins to integrate with external tools like Git, AWS, Docker, Slack, or SonarQube.', difficulty: 'Basic' },
  { id: 'd13', category: 'DevOps & CI/CD', question: 'What is Infrastructure as Code (IaC)?', answer: 'IaC is the process of managing and provisioning computing infrastructure through machine-readable definition files (like Ansible YAML or Terraform HCL) rather than physical hardware configuration or interactive configuration tools (like clicking through a web UI).', difficulty: 'Intermediate' },
  { id: 'd14', category: 'DevOps & CI/CD', question: 'What is a webhook?', answer: 'A webhook is a method for one application to provide real-time information to another application. It sends an HTTP POST payload to a configured URL when a specific event occurs, like pushing code to a Git repository.', difficulty: 'Basic' },
  { id: 'd15', category: 'DevOps & CI/CD', question: 'In Ansible, what is the inventory file?', answer: 'The inventory file is a text file that lists all the remote nodes (servers) that Ansible manages. It can organize servers into groups (like [webservers] or [dbservers]), allowing you to run playbooks against specific clusters.', difficulty: 'Intermediate' }
];
