import { Question } from './types';

export const awsQuestions: Question[] = [
  { id: 'a1', category: 'AWS Cloud', question: 'What is an EC2 instance, and how did you secure it in your project?', answer: 'Amazon EC2 (Elastic Compute Cloud) is a virtual server in the AWS cloud. I secured it by configuring Security Groups (acting as a virtual firewall) to only allow inbound traffic on specific ports like TCP 22 for SSH (from my IP only) and TCP 80/443 for HTTP/HTTPS. I also used SSH key pairs for authentication instead of passwords.', difficulty: 'Basic' },
  { id: 'a2', category: 'AWS Cloud', question: 'How do you host a static website on AWS S3?', answer: '1. Create an S3 bucket with the exact domain name. 2. Enable "Static website hosting" in the bucket properties. 3. Upload the HTML/CSS/JS files (like index.html). 4. Disable "Block all public access". 5. Add a Bucket Policy granting `s3:GetObject` permission to public (`*`) for all objects in the bucket.', difficulty: 'Intermediate' },
  { id: 'a3', category: 'AWS Cloud', question: 'What is IAM, and explain the principle of least privilege.', answer: 'AWS IAM (Identity and Access Management) controls access to AWS resources. The principle of least privilege means granting a user or service only the minimum permissions necessary to perform their specific job, and nothing more. This minimizes the risk of accidental or malicious damage.', difficulty: 'Basic' },
  { id: 'a4', category: 'AWS Cloud', question: 'Difference between an IAM Role and an IAM User?', answer: 'An IAM User represents a specific person or application with permanent credentials (password or access keys). An IAM Role does not have permanent credentials; instead, it is temporarily assumed by a user, an AWS service (like an EC2 instance), or an external identity to gain permissions dynamically.', difficulty: 'Intermediate' },
  { id: 'a5', category: 'AWS Cloud', question: 'What is Amazon CloudWatch, and how did you use it?', answer: 'CloudWatch is a monitoring and management service in AWS. I used it to monitor the CPU utilization, network traffic, and disk read/write operations of my EC2 instances. It can also be used to set alarms (e.g., if CPU goes above 80%) to trigger auto-scaling or send email notifications via SNS.', difficulty: 'Intermediate' },
  { id: 'a6', category: 'AWS Cloud', question: 'What is a VPC, and what are its basic components?', answer: 'Amazon VPC (Virtual Private Cloud) is an isolated private network in the AWS cloud. Basic components include Subnets (Public and Private), Route Tables (to direct traffic), an Internet Gateway (to allow public subnets to access the internet), and Security Groups/NACLs for security.', difficulty: 'Intermediate' },
  { id: 'a7', category: 'AWS Cloud', question: 'What is the difference between Security Groups and Network ACLs (NACLs)?', answer: 'Security Groups operate at the instance level, are stateful (return traffic is automatically allowed), and only support allow rules. NACLs operate at the subnet level, are stateless (return traffic must be explicitly allowed), and support both allow and deny rules.', difficulty: 'Advanced' },
  { id: 'a8', category: 'AWS Cloud', question: 'Explain the difference between an EBS volume and Instance Store.', answer: 'EBS (Elastic Block Store) is persistent network-attached storage that survives instance stops/terminations. Instance Store is temporary block storage located on disks physically attached to the host computer; data is lost if the instance stops or terminates.', difficulty: 'Intermediate' },
  { id: 'a9', category: 'AWS Cloud', question: 'What are AWS Regions and Availability Zones (AZs)?', answer: 'A Region is a distinct geographical location (like us-east-1). An Availability Zone is one or more discrete data centers with redundant power, networking, and connectivity within a Region. AZs provide high availability and fault tolerance.', difficulty: 'Basic' },
  { id: 'a10', category: 'AWS Cloud', question: 'If your EC2 instance is unreachable via SSH, what could be the reasons?', answer: 'Reasons include: 1. Security group not allowing port 22. 2. NACL blocking port 22 or ephemeral ports. 3. No Internet Gateway attached to the VPC. 4. Instance is in a private subnet without a jump host/VPN. 5. Using the wrong SSH key pair. 6. The EC2 instance state is not running.', difficulty: 'Advanced' },
  { id: 'a11', category: 'AWS Cloud', question: 'How can you securely store access keys and secrets instead of hardcoding them?', answer: 'You can use AWS Secrets Manager or AWS Systems Manager Parameter Store to securely store and retrieve secrets dynamically. Alternatively, assign an IAM Role to the EC2 instance so it doesn\'t need long-term credentials at all.', difficulty: 'Intermediate' },
  { id: 'a12', category: 'AWS Cloud', question: 'What is AWS Auto Scaling?', answer: 'AWS Auto Scaling automatically adjusts the number of compute resources (like EC2 instances) in response to incoming traffic or metrics (like CPU utilization) defined in CloudWatch alarms, ensuring performance and reducing costs when demand drops.', difficulty: 'Basic' },
  { id: 'a13', category: 'AWS Cloud', question: 'How do you restrict access to an S3 bucket to only specific IP addresses?', answer: 'You can attach an S3 Bucket Policy containing a "Condition" block that uses the `IpAddress` operator with `aws:SourceIp`, specifying the allowed IP range (CIDR block).', difficulty: 'Advanced' },
  { id: 'a14', category: 'AWS Cloud', question: 'What is an Elastic IP address?', answer: 'An Elastic IP address is a static, public IPv4 address assigned to an AWS account. Unlike a default public IP, an Elastic IP does not change when an EC2 instance is stopped and started.', difficulty: 'Basic' },
  { id: 'a15', category: 'AWS Cloud', question: 'Explain what an AMI (Amazon Machine Image) is.', answer: 'An AMI is a master image used to launch EC2 instances. It contains the operating system (like Ubuntu or CentOS), application server, and applications required to run your environment.', difficulty: 'Basic' },
  { id: 'a16', category: 'AWS Cloud', question: 'What is Amazon Route 53?', answer: 'Amazon Route 53 is a highly available and scalable cloud Domain Name System (DNS) web service. It connects user requests to infrastructure running in AWS (like EC2, Load Balancers, or S3 buckets) and can also route users to infrastructure outside of AWS.', difficulty: 'Intermediate' },
  { id: 'a17', category: 'AWS Cloud', question: 'How can you cost-optimize your AWS EC2 infrastructure?', answer: '1. Use Reserved Instances or Savings Plans for predictable workloads. 2. Use Spot Instances for flexible/batch workloads. 3. Stop instances when not in use (e.g., dev/test environments). 4. Use Auto Scaling to match demand. 5. Right-size instances based on CloudWatch metrics.', difficulty: 'Advanced' },
  { id: 'a18', category: 'AWS Cloud', question: 'What is the purpose of an Internet Gateway (IGW)?', answer: 'An Internet Gateway is a horizontally scaled, redundant, and highly available VPC component that allows communication between resources in your VPC (like public subnets) and the internet.', difficulty: 'Basic' },
  { id: 'a19', category: 'AWS Cloud', question: 'What is AWS CloudTrail?', answer: 'AWS CloudTrail is a service that enables governance, compliance, operational auditing, and risk auditing of your AWS account. It logs continuous records of actions taken by users, roles, and AWS services (API calls).', difficulty: 'Intermediate' },
  { id: 'a20', category: 'AWS Cloud', question: 'How do you implement a backup strategy for EC2?', answer: 'You can take periodic EBS Snapshots to back up the data on the EBS volumes. These can be automated using Amazon Data Lifecycle Manager (DLM) or AWS Backup.', difficulty: 'Intermediate' }
];
