import { Question } from './types';

export const webQuestions: Question[] = [
  { id: 'w1', category: 'Web Services & Databases', question: 'How do you install and configure the Apache HTTP Server on Linux?', answer: 'On Ubuntu/Debian, use `sudo apt install apache2`. On CentOS/RHEL, use `sudo yum install httpd`. Once installed, you start the service using `systemctl start httpd` and enable it on boot using `systemctl enable httpd`. Web files are placed in `/var/www/html/`.', difficulty: 'Basic' },
  { id: 'w2', category: 'Web Services & Databases', question: 'What is MariaDB, and how do you perform basic CRUD operations?', answer: 'MariaDB is a relational database fork of MySQL. CRUD stands for Create, Read, Update, Delete. Create: `INSERT INTO users (name) VALUES ("Sahil");` Read: `SELECT * FROM users;` Update: `UPDATE users SET name="Sayyed" WHERE id=1;` Delete: `DELETE FROM users WHERE id=1;`', difficulty: 'Basic' },
  { id: 'w3', category: 'Web Services & Databases', question: 'Explain the difference between TCP and UDP.', answer: 'TCP (Transmission Control Protocol) is connection-oriented, reliable, and ensures data packets arrive in order (used in HTTP, SSH). UDP (User Datagram Protocol) is connectionless, faster, but does not guarantee delivery or order (used in DNS, video streaming).', difficulty: 'Basic' },
  { id: 'w4', category: 'Web Services & Databases', question: 'What is DNS and how does it resolve a domain name?', answer: 'DNS (Domain Name System) translates human-readable domain names (like google.com) into IP addresses. Resolution process: 1. Browser checks local cache. 2. Queries OS cache. 3. Queries ISP Resolver. 4. Resolver queries Root server -> TLD server -> Authoritative Name Server to fetch the IP.', difficulty: 'Intermediate' },
  { id: 'w5', category: 'Web Services & Databases', question: 'How do you grant permissions to a specific user in MariaDB?', answer: 'You log into the database as root and use the GRANT command. Example: `GRANT ALL PRIVILEGES ON mydatabase.* TO "myuser"@"localhost" IDENTIFIED BY "mypassword";` followed by `FLUSH PRIVILEGES;`.', difficulty: 'Intermediate' },
  { id: 'w6', category: 'Web Services & Databases', question: 'What is the default port for Apache, and how can you change it?', answer: 'The default port is 80 for HTTP and 443 for HTTPS. To change it, edit the configuration file (e.g., `/etc/apache2/ports.conf` in Ubuntu or `/etc/httpd/conf/httpd.conf` in CentOS), change `Listen 80` to your desired port, and restart the service.', difficulty: 'Intermediate' },
  { id: 'w7', category: 'Web Services & Databases', question: 'What is the difference between a Relational (SQL) and Non-Relational (NoSQL) database?', answer: 'Relational databases (like MariaDB, MySQL) store data in structured tables with rows and columns, enforcing strict schemas and using SQL. Non-Relational databases (like MongoDB) store data in flexible formats like JSON documents, key-value pairs, or graphs, suitable for unstructured data.', difficulty: 'Basic' },
  { id: 'w8', category: 'Web Services & Databases', question: 'Explain HTTP status codes 200, 404, and 500.', answer: '200 OK: The request succeeded. 404 Not Found: The server cannot find the requested resource. 500 Internal Server Error: The server encountered an unexpected condition that prevented it from fulfilling the request.', difficulty: 'Basic' },
  { id: 'w9', category: 'Web Services & Databases', question: 'How do you backup and restore a MariaDB database?', answer: 'To backup: Use `mysqldump -u username -p databasename > backup.sql`. To restore: Use `mysql -u username -p databasename < backup.sql`.', difficulty: 'Intermediate' },
  { id: 'w10', category: 'Web Services & Databases', question: 'What is a Virtual Host in Apache?', answer: 'Virtual Hosting allows a single Apache server instance to host multiple websites or domains (like site1.com and site2.com). It routes incoming requests to the correct document root based on the domain name in the HTTP host header.', difficulty: 'Advanced' }
];
