import { Question } from './types';

export const ciscoQuestions: Question[] = [
  { id: 'n1', category: 'Cisco Networking', question: 'What is a VLAN and why is it used?', answer: 'VLAN stands for Virtual Local Area Network. It logically segments a physical network into multiple distinct broadcast domains at Layer 2. It is used to improve security (isolating departments), reduce broadcast traffic, and simplify network management without needing separate physical switches.', difficulty: 'Basic' },
  { id: 'n2', category: 'Cisco Networking', question: 'How does Inter-VLAN routing work?', answer: 'Since VLANs are isolated, devices in different VLANs cannot communicate directly. Inter-VLAN routing uses a Layer 3 device (like a router or a Layer 3 switch) to route traffic between them. A common method is "Router on a Stick," where a single router interface is divided into sub-interfaces, each tagged with a specific VLAN ID (using 802.1Q encapsulation).', difficulty: 'Intermediate' },
  { id: 'n3', category: 'Cisco Networking', question: 'Explain the DORA process in DHCP.', answer: 'DORA explains how a client gets an IP from a DHCP server. 1. Discover (Client broadcasts looking for a server). 2. Offer (Server offers an IP address). 3. Request (Client requests the offered IP). 4. Acknowledge (Server acknowledges and assigns the IP, subnet mask, and gateway).', difficulty: 'Intermediate' },
  { id: 'n4', category: 'Cisco Networking', question: 'What is subnetting, and why did you apply it in your project?', answer: 'Subnetting is the process of dividing a large network into smaller, manageable sub-networks (subnets). I used it to optimize IP address allocation, reduce broadcast domains, and organize the network logically (e.g., separate subnets for HR, IT, and Sales) while preventing IP wastage.', difficulty: 'Basic' },
  { id: 'n5', category: 'Cisco Networking', question: 'What is the difference between a switch and a router?', answer: 'A Switch operates at Layer 2 (Data Link) and connects devices within the same network using MAC addresses. A Router operates at Layer 3 (Network) and connects different networks together, routing data packets based on IP addresses.', difficulty: 'Basic' },
  { id: 'n6', category: 'Cisco Networking', question: 'What is the 802.1Q protocol?', answer: '802.1Q is a networking standard that supports Virtual LANs (VLANs) on an Ethernet network. It inserts a 4-byte VLAN tag into the Ethernet frame header, allowing a single physical link (trunk port) to carry traffic for multiple VLANs and keeping them logically separated.', difficulty: 'Advanced' },
  { id: 'n7', category: 'Cisco Networking', question: 'What is the difference between an Access Port and a Trunk Port?', answer: 'An Access Port belongs to and carries the traffic of only one specific VLAN (used for connecting end devices like PCs). A Trunk Port can carry traffic for multiple VLANs simultaneously, using 802.1Q tagging to distinguish them (used for connections between switches or switches and routers).', difficulty: 'Intermediate' },
  { id: 'n8', category: 'Cisco Networking', question: 'Explain the OSI Model layers in order.', answer: 'Please Do Not Throw Sausage Pizza Away. 1. Physical (Cables), 2. Data Link (Switches/MAC), 3. Network (Routers/IP), 4. Transport (TCP/UDP), 5. Session, 6. Presentation, 7. Application (HTTP/DNS).', difficulty: 'Basic' },
  { id: 'n9', category: 'Cisco Networking', question: 'What is a Default Gateway?', answer: 'A Default Gateway is the IP address of the router interface that serves as an exit point for a local network. If a PC needs to communicate with a device on a different subnet or the internet, it sends the packet to the default gateway.', difficulty: 'Basic' },
  { id: 'n10', category: 'Cisco Networking', question: 'What is ARP and how does it work?', answer: 'ARP (Address Resolution Protocol) maps an IP address to a MAC address. When a device knows the destination IP but not the MAC address, it broadcasts an ARP Request ("Who has this IP?"). The target device replies with an ARP Reply containing its MAC address.', difficulty: 'Intermediate' },
  { id: 'n11', category: 'Cisco Networking', question: 'How do you assign an IP address to a Cisco switch for management?', answer: 'You assign the IP address to a virtual interface (SVI), typically VLAN 1. Commands: `interface vlan 1` -> `ip address <ip> <mask>` -> `no shutdown`.', difficulty: 'Intermediate' },
  { id: 'n12', category: 'Cisco Networking', question: 'What is a static route?', answer: 'A static route is a manually configured path in a router\'s routing table. It explicitly tells the router which interface or next-hop IP address to use to reach a specific destination network. It is not dynamically updated if the network topology changes.', difficulty: 'Basic' },
  { id: 'n13', category: 'Cisco Networking', question: 'Calculate the subnet mask and number of hosts for a /26 network.', answer: 'A /26 network uses 26 bits for the network, leaving 6 bits for hosts. The subnet mask is 255.255.255.192. Total hosts = 2^6 = 64. Usable hosts = 64 - 2 (network & broadcast) = 62.', difficulty: 'Advanced' },
  { id: 'n14', category: 'Cisco Networking', question: 'What is the purpose of ping and traceroute?', answer: '`ping` uses ICMP Echo Requests to test end-to-end connectivity and measure latency to a destination. `traceroute` (or tracert) maps the exact path (hop-by-hop) a packet takes to reach the destination, helping identify where a network connection drops.', difficulty: 'Basic' },
  { id: 'n15', category: 'Cisco Networking', question: 'What is a MAC Address?', answer: 'A MAC (Media Access Control) address is a unique 48-bit hardware address assigned to a network interface card (NIC) by the manufacturer. It operates at Layer 2 and is used for local network delivery.', difficulty: 'Basic' },
  { id: 'n16', category: 'Cisco Networking', question: 'How do you secure access to a Cisco router\'s CLI?', answer: '1. Set an enable secret password (encrypted). 2. Set passwords on the console line. 3. Set passwords on the VTY lines (for Telnet/SSH). 4. Use SSH instead of Telnet. 5. Create local usernames and passwords.', difficulty: 'Intermediate' },
  { id: 'n17', category: 'Cisco Networking', question: 'What is STP (Spanning Tree Protocol)?', answer: 'STP is a Layer 2 protocol used to prevent routing loops in a network with redundant paths. It does this by electing a Root Bridge and blocking redundant links, keeping them as backups in case the primary link fails.', difficulty: 'Advanced' },
  { id: 'n18', category: 'Cisco Networking', question: 'Explain the difference between TCP and UDP.', answer: 'TCP (Transmission Control Protocol) is connection-oriented, reliable, and uses handshakes and acknowledgments to ensure data arrives sequentially (used for web, SSH). UDP (User Datagram Protocol) is connectionless and faster but doesn\'t guarantee delivery or order (used for video streaming, DNS).', difficulty: 'Intermediate' },
  { id: 'n19', category: 'Cisco Networking', question: 'What is NAT (Network Address Translation)?', answer: 'NAT translates private, non-routable IP addresses on an internal network into a single or multiple public IP addresses before packets are forwarded to the internet, preserving IPv4 addresses and adding a layer of security.', difficulty: 'Intermediate' },
  { id: 'n20', category: 'Cisco Networking', question: 'What does the command `show ip interface brief` do?', answer: 'It provides a quick, concise summary of all interfaces on a router or switch, showing their IP addresses, physical layer status (up/down), and data link layer status (up/down).', difficulty: 'Basic' }
];
