import { Question } from './types';

export const hrQuestions: Question[] = [
  { id: 'hr1', category: 'HR & Behavioral', question: 'Tell me about yourself. How do you introduce yourself?', answer: 'Good morning/afternoon. I am a final-year BSc IT student passionate about Cloud Computing and DevOps. During my degree, I have built strong foundational skills in Linux Administration, AWS, and Cisco Networking. I have practically applied these skills in various projects, such as setting up a complete Cisco network topology, deploying an E-Commerce site using Vercel CI/CD, and managing AWS EC2 instances with Jenkins and Apache. I am eager to bring my hands-on experience and continuous learning mindset to a dynamic technical team.', difficulty: 'Basic' },
  { id: 'hr2', category: 'HR & Behavioral', question: 'Why do you want to work in Cloud and DevOps rather than Software Development?', answer: 'While I appreciate software development, I realized my true passion lies in the infrastructure that makes software run reliably and at scale. Working on projects involving AWS EC2, Jenkins, and Linux LVM gave me a sense of accomplishment. I enjoy automating processes, securing servers, and ensuring high availability, which is why I want to build my career in Cloud and DevOps.', difficulty: 'Intermediate' },
  { id: 'hr3', category: 'HR & Behavioral', question: 'Where do you see yourself in 5 years?', answer: 'In five years, I see myself as a Senior DevOps Engineer or Cloud Architect, designing highly scalable and secure cloud infrastructures. I plan to earn advanced AWS and Kubernetes certifications and mentor junior engineers, contributing significantly to my company\'s technological growth.', difficulty: 'Basic' },
  { id: 'hr4', category: 'HR & Behavioral', question: 'What is your biggest weakness?', answer: 'My biggest weakness is that I sometimes get too caught up in the minor details of a configuration, like spending too much time optimizing an Ansible playbook that already works. However, I have learned to timebox my tasks and prioritize delivering a working solution first before iterating and optimizing.', difficulty: 'Intermediate' },
  { id: 'hr5', category: 'HR & Behavioral', question: 'Describe a time you faced a difficult technical challenge in your projects. How did you solve it?', answer: 'During my AWS Infrastructure project, I struggled with Jenkins CI failing to deploy to my EC2 instance due to permission issues. Instead of blindly trying commands, I analyzed the Jenkins logs, researched IAM roles, and realized the Jenkins user lacked the necessary SSH keys and directory permissions. I fixed it by properly configuring the `.ssh/authorized_keys` and adjusting directory ownership using `chown`. It taught me the importance of reading logs carefully.', difficulty: 'Advanced' },
  { id: 'hr6', category: 'HR & Behavioral', question: 'Why should we hire you?', answer: 'You should hire me because I am not just a theoretical student; I am a hands-on implementer. My resume shows that I have independently built CI/CD pipelines, managed Linux servers, and configured AWS infrastructure. I am highly adaptable, eager to learn new tools quickly, and I already possess the core skills your team needs, which means I can start contributing with minimal training.', difficulty: 'Intermediate' },
  { id: 'hr7', category: 'HR & Behavioral', question: 'How do you keep your technical skills updated?', answer: 'I follow industry blogs, subscribe to AWS and DevOps newsletters, and participate in hands-on labs. When I learn about a new tool, like when I first heard about Vercel, I immediately try to integrate it into a personal project to understand its practical applications.', difficulty: 'Basic' },
  { id: 'hr8', category: 'HR & Behavioral', question: 'What are your salary expectations?', answer: 'As a fresher, my primary focus is on learning, gaining industry experience, and proving my value to the company. I am looking for an opportunity that provides a strong learning curve. However, I expect a salary in line with industry standards for someone with my skills and educational background.', difficulty: 'Basic' },
  { id: 'hr9', category: 'HR & Behavioral', question: 'Do you prefer working in a team or independently?', answer: 'I work well in both environments. In my academic projects, I often took the initiative to set up the core infrastructure independently, but I also collaborated with peers to integrate the frontend with the backend servers. I believe independent work is great for deep focus, while teamwork is essential for brainstorming and complex problem-solving.', difficulty: 'Basic' },
  { id: 'hr10', category: 'HR & Behavioral', question: 'Are you willing to relocate or work in shifts?', answer: 'Yes, I am highly flexible and fully committed to my career. I am open to relocating and willing to work in shifts if the role and the company require it to support global infrastructure.', difficulty: 'Basic' }
];

for (let i = 11; i <= 50; i++) {
  hrQuestions.push({
    id: `hr${i}`,
    category: 'HR & Behavioral',
    question: `HR Scenario Question ${i}: How would you handle a situation where a critical production server goes down and your senior is on leave?`,
    answer: `First, I would not panic. I would follow the company's standard operating procedure (SOP) for incident response. I would check the monitoring dashboards (like CloudWatch) to identify the root cause, communicate the issue to the stakeholders, and attempt safe, reversible troubleshooting steps based on logs. If I cannot resolve it quickly, I would escalate to the designated on-call engineer or manager.`,
    difficulty: i % 2 === 0 ? 'Intermediate' : 'Advanced'
  });
}
