import { Question } from './types';

export const linuxQuestions: Question[] = [
  { id: 'l1', category: 'Linux Administration', question: 'What is the exact difference between CentOS and Ubuntu?', answer: 'CentOS is based on Red Hat Enterprise Linux (RHEL) and uses the YUM/DNF package manager with .rpm packages. Ubuntu is based on Debian and uses the APT package manager with .deb packages. In enterprise environments, CentOS was historically preferred for server stability, while Ubuntu is popular for cloud and developer environments.', difficulty: 'Basic' },
  { id: 'l2', category: 'Linux Administration', question: 'How do you check disk space usage in Linux? Explain df vs du.', answer: 'The `df` (disk free) command displays the amount of available disk space for file systems (e.g., `df -h` for human-readable format). The `du` (disk usage) command estimates file space usage for specific directories or files (e.g., `du -sh /var/log` to see the total size of the log directory).', difficulty: 'Basic' },
  { id: 'l3', category: 'Linux Administration', question: 'What is LVM and why did you use it in your project?', answer: 'LVM stands for Logical Volume Manager. It provides a layer of abstraction over physical storage, allowing us to create logical volumes that can be easily resized, extended, or reduced without downtime. I used it in my project to manage storage flexibly, allowing me to add more physical disks to a volume group and extend logical volumes online without unmounting.', difficulty: 'Intermediate' },
  { id: 'l4', category: 'Linux Administration', question: 'Can you explain the steps to extend an LVM volume?', answer: '1. Create a new Physical Volume (PV) using `pvcreate /dev/sdb`. 2. Extend the Volume Group (VG) using `vgextend my_vg /dev/sdb`. 3. Extend the Logical Volume (LV) using `lvextend -L +10G /dev/my_vg/my_lv`. 4. Finally, resize the file system to use the new space using `resize2fs /dev/my_vg/my_lv` (for ext4) or `xfs_growfs` (for XFS).', difficulty: 'Advanced' },
  { id: 'l5', category: 'Linux Administration', question: 'Explain the difference between chmod and chown.', answer: '`chmod` (change mode) is used to change the read, write, and execute permissions of a file or directory for the owner, group, and others. `chown` (change owner) is used to change the user ownership and group ownership of a file or directory.', difficulty: 'Basic' },
  { id: 'l6', category: 'Linux Administration', question: 'What does the permission "755" mean on a directory?', answer: '755 means the owner has read, write, and execute permissions (4+2+1 = 7). The group has read and execute permissions (4+1 = 5). Others have read and execute permissions (4+1 = 5). For a directory, "execute" means the ability to enter/cd into it.', difficulty: 'Intermediate' },
  { id: 'l7', category: 'Linux Administration', question: 'How do you troubleshoot network connectivity issues from a Linux server?', answer: 'I would start by checking local IP configuration using `ip a`. Then, test basic connectivity using `ping <IP>`. If it fails, I check the routing table with `ip route`. To see where packets are dropping, I use `traceroute`. To check if specific ports are listening or established, I use `netstat -tulpn` or the modern equivalent `ss -tulpn`.', difficulty: 'Intermediate' },
  { id: 'l8', category: 'Linux Administration', question: 'What is Samba, and how did you configure it?', answer: 'Samba is an open-source implementation of the SMB/CIFS protocol, used for sharing files and printers between Linux and Windows systems over a network. I configured it by editing the `/etc/samba/smb.conf` file, defining a shared directory, setting valid users/permissions, restarting the `smbd` service, and setting up Samba passwords using `smbpasswd`.', difficulty: 'Intermediate' },
  { id: 'l9', category: 'Linux Administration', question: 'What are the physical volume (PV), volume group (VG), and logical volume (LV)?', answer: 'PV is the actual physical hard drive or partition. VG is a storage pool created by combining one or more PVs. LV is the usable storage space carved out of a VG, which can be formatted with a file system and mounted. This hierarchy (PV -> VG -> LV) is the core of LVM.', difficulty: 'Intermediate' },
  { id: 'l10', category: 'Linux Administration', question: 'How do you view running processes and kill a stuck process?', answer: 'I can view processes using `top`, `htop`, or `ps aux`. To kill a process, I first find its PID (Process ID) and then use `kill <PID>`. If it refuses to terminate gracefully, I use `kill -9 <PID>` to forcefully kill it (SIGKILL).', difficulty: 'Basic' },
  { id: 'l11', category: 'Linux Administration', question: 'What command is used to find files in Linux by name or extension?', answer: 'The `find` command is used. For example, `find / -name "*.txt"` searches the entire root directory for text files. You can also use `locate`, but it relies on a pre-built database that needs to be updated with `updatedb`.', difficulty: 'Basic' },
  { id: 'l12', category: 'Linux Administration', question: 'Explain the boot process of a Linux system.', answer: '1. BIOS/UEFI performs POST (Power-On Self Test) and finds the bootable drive. 2. MBR/GPT loads the bootloader (like GRUB). 3. GRUB loads the kernel into memory. 4. Kernel mounts the root filesystem and starts the init system (like systemd). 5. systemd starts required services and brings up the user space environment.', difficulty: 'Advanced' },
  { id: 'l13', category: 'Linux Administration', question: 'How do you check the open ports on a Linux server?', answer: 'You can use `ss -tuln` (preferred modern way) or `netstat -tuln`. This will show all TCP (t) and UDP (u) listening (l) ports with numeric (n) IP addresses and port numbers.', difficulty: 'Intermediate' },
  { id: 'l14', category: 'Linux Administration', question: 'What is the purpose of the /etc/fstab file?', answer: 'The `/etc/fstab` (file systems table) file contains static information about the file systems. It defines how and where partitions, logical volumes, and remote shares should be automatically mounted when the system boots up.', difficulty: 'Intermediate' },
  { id: 'l15', category: 'Linux Administration', question: 'How would you find out which process is using a specific port?', answer: 'I would use `lsof -i :<port_number>` or `ss -lptn \'sport = :<port_number>\'`. You need root or sudo privileges to see process names and PIDs for processes you do not own.', difficulty: 'Advanced' },
  { id: 'l16', category: 'Linux Administration', question: 'What is a soft link and a hard link?', answer: 'A soft link (symlink) is like a shortcut; it points to the file name. If the original file is deleted, the soft link breaks. A hard link points to the inode of the original file. If the original file is deleted, the data remains as long as the hard link exists. Created with `ln -s` (soft) and `ln` (hard).', difficulty: 'Intermediate' },
  { id: 'l17', category: 'Linux Administration', question: 'How do you securely copy a file from your local machine to a Linux server?', answer: 'You can use `scp` (Secure Copy). Command: `scp localfile.txt user@server_ip:/remote/path/`. Alternatively, you can use `rsync` or `sftp` over SSH.', difficulty: 'Basic' },
  { id: 'l18', category: 'Linux Administration', question: 'Explain the difference between su and sudo.', answer: '`su` (substitute user) switches your current shell to another user (usually root) and requires that user\'s password. `sudo` (superuser do) executes a single command as another user (usually root) but requires your own password, and your user must be in the sudoers file.', difficulty: 'Basic' },
  { id: 'l19', category: 'Linux Administration', question: 'What is systemd and how do you manage services with it?', answer: 'systemd is the init system and service manager for most modern Linux distributions (CentOS 7+, Ubuntu 16.04+). You use the `systemctl` command. Examples: `systemctl start service_name`, `systemctl stop service_name`, `systemctl status service_name`, `systemctl enable service_name` (start on boot).', difficulty: 'Intermediate' },
  { id: 'l20', category: 'Linux Administration', question: 'How do you check real-time log files in Linux?', answer: 'You can use the `tail -f` command to output appended data as the file grows. For example, `tail -f /var/log/syslog` or `tail -f /var/log/messages`. For systemd journals, you use `journalctl -f`.', difficulty: 'Basic' }
];
